### ISSUE TITLE
[Object>>doesNotUnderstad: aMessage (ensureCreateDirectory)] encountered after loading Shapes into Pharo 10

### ISSUE THREAD

**Issue by capsulecorplab** [hernanmd/Shapes#2]
I keep encountering this error every time I try to open or click on a playground window after having loaded `Shapes` into Pharo 10 with Metacello...
![Screenshot from 2022-09-22 13-18-52](https://user-images.githubusercontent.com/14095576/191833873-bb4b5eb1-5267-4aac-b032-8995a07c2fcd.png)
![Screenshot from 2022-09-22 13-20-05](https://user-images.githubusercontent.com/14095576/191833892-301e6e0a-7136-4832-8a35-d0c1065df057.png)

**Comment by hernanmd** [comment]
Fix merged in master branch.
